services:
  - type: web
    name: peppal-backend
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn peppal_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: peppal_backend.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "peppal-backend.onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1" 