# Generated by Django 5.2 on 2025-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journalentry_remove_moodentry_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindnessChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='timestamp',
        ),
    ]
